# ACM format profile - render with: quarto render --profile acm --to acm-pdf
format:
  acm-pdf:
    output-file: index-acm.pdf
    format: sigconf
    echo: false
    keep-tex: true
    fig-width: 3.33
    fig-height: 2.5
    fig-format: pdf
    biblio-style: ACM-Reference-Format
    include-in-header:
      - text: |
          \usepackage{tabularray}
          \usepackage{float}
          \usepackage{graphicx}
          \usepackage{rotating}
          \usepackage[normalem]{ulem}
          \usepackage{colortbl}
          \usepackage{booktabs}
          \UseTblrLibrary{booktabs}
    acm-metadata:
      anonymous: true
      copyright: none
      copyright-year: "2026"
      acm-year: "2026"
      conference-acronym: "CHI PLAY '26"
      conference-name: "ACM SIGCHI Annual Symposium on Computer-Human Interaction in Play"
      conference-date: "November 2--5, 2026"
      conference-location: "York, UK"
      ccs: |
        \ccsdesc[500]{Human-centered computing~Empirical studies in HCI}
        \ccsdesc[300]{Human-centered computing~Empirical studies in collaborative and social computing}
