project:
  type: website
  execute-dir: project
  output-dir: _site
  render:
    - index.qmd

execute:
  freeze: true

repo-url: https://github.com/nballou/open-play-demographics
site-url: https://nballou.github.io/open-play-demographics/
data-url: https://example.com
data-license: CC0